development:
  adapter: postgresql
  encoding: unicode
  database: super-voices_development
  pool: 5
  username: super-voices
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: super-voices_test
  pool: 5
  username: super-voices
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: super-voices
  pool: 5
  username: super-voices
  password:
